apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: my-service
spec:
  host: web
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-service
spec:
  hosts:
  - web
  http:
  - match:
    - headers:
        version:
          exact: "v2"
    route:
    - destination:
        host: web
        subset: v2
  - match:
    - headers:
        version:
          exact: "v1"
    route:
    - destination:
        host: web
        subset: v1
  - route:
    - destination:
        host: web
        subset: v1
      weight: 50
    - destination:
        host: web
        subset: v2
      weight: 50
      
# v1 为 生产版本 v2 为新版本
# 默认 header头调用v1版本，如果需要，通过前端传给后端v2版本，来验证v2版本
# 如果只想测试v2新版本，则配置header version:v2
# 如果只想测试v1老版本，则配置header version:v1
# 如果两个版本共存，则默认访问比例为 1:1，这时候，不需要添加header头，前期可以修改版本比例为: 100:0，等v2版本验证通过后，再调整为 50:50
